from __future__ import annotations
from pathlib import Path
from datetime import datetime, timezone
from ryva.utils import load_manifest, console
from rich.panel import Panel


def generate_docs(root: Path) -> None:
    manifest = load_manifest(root)
    docs_dir = root / "target" / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    _write_index(docs_dir, manifest)
    for name, agent in manifest.get("agents", {}).items():
        _write_agent_doc(docs_dir, name, agent)
    for name, tool in manifest.get("tools", {}).items():
        _write_tool_doc(docs_dir, name, tool)

    console.print(Panel(
        f"[bold green]✓ Docs generated[/bold green]\n[dim]Output: target/docs/[/dim]",
        expand=False
    ))


def _write_index(docs_dir: Path, manifest: dict) -> None:
    project = manifest.get("project", {})
    agents = manifest.get("agents", {})
    tools = manifest.get("tools", {})
    pipelines = manifest.get("pipelines", {})
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# {project.get('name', 'Ryva Project')}",
        f"",
        f"> Generated by Ryva on {ts}",
        f"",
        f"## Agents ({len(agents)})",
        "",
    ]
    for name, agent in agents.items():
        desc = agent.get("description", "")
        lines.append(f"- [{name}](agents/{name}.md) — {desc}")

    lines += ["", f"## Tools ({len(tools)})", ""]
    for name, tool in tools.items():
        desc = tool.get("description", "")
        lines.append(f"- [{name}](tools/{name}.md) — {desc}")

    lines += ["", f"## Pipelines ({len(pipelines)})", ""]
    for name, pipeline in pipelines.items():
        desc = pipeline.get("description", "")
        lines.append(f"- **{name}** — {desc}")

    (docs_dir / "index.md").write_text("\n".join(lines))


def _write_agent_doc(docs_dir: Path, name: str, agent: dict) -> None:
    (docs_dir / "agents").mkdir(exist_ok=True)
    lines = [
        f"# Agent: {name}",
        f"",
        f"**Version:** {agent.get('version', '?')}  ",
        f"**Description:** {agent.get('description', '—')}  ",
        f"**Model:** {agent.get('model', 'project default')}  ",
    ]

    tags = agent.get("tags", [])
    if tags:
        lines.append(f"**Tags:** {', '.join(tags)}  ")

    meta = agent.get("meta", {})
    if meta:
        lines += ["", "## Metadata", ""]
        for k, v in meta.items():
            lines.append(f"- **{k}:** {v}")

    inp = agent.get("input", {}) or {}
    if inp.get("schema"):
        lines += ["", "## Input Schema", "", "| Field | Type | Required | Default |", "|---|---|---|---|"]
        for field, spec in inp["schema"].items():
            lines.append(f"| {field} | {spec.get('type','any')} | {spec.get('required', False)} | {spec.get('default', '—')} |")

    out = agent.get("output", {}) or {}
    if out.get("schema"):
        lines += ["", "## Output Schema", "", "| Field | Type |", "|---|---|"]
        for field, spec in out["schema"].items():
            lines.append(f"| {field} | {spec.get('type','any')} |")

    tools = agent.get("tools", [])
    if tools:
        lines += ["", "## Tools", ""]
        for t in tools:
            lines.append(f"- `{t}`")

    tests = agent.get("tests", [])
    if tests:
        lines += ["", "## Tests", ""]
        for t in tests:
            lines.append(f"- **{t.get('type')}**" + (f": threshold {t.get('threshold')}ms" if t.get("threshold") else ""))

    (docs_dir / "agents" / f"{name}.md").write_text("\n".join(lines))


def _write_tool_doc(docs_dir: Path, name: str, tool: dict) -> None:
    (docs_dir / "tools").mkdir(exist_ok=True)
    lines = [
        f"# Tool: {name}",
        f"",
        f"**Version:** {tool.get('version', '?')}  ",
        f"**Description:** {tool.get('description', '—')}  ",
        f"**Implementation:** `{tool.get('implementation', '?')}`  ",
        f"**Function:** `{tool.get('function', 'run')}`  ",
    ]

    inp = tool.get("input", {}) or {}
    if inp.get("schema"):
        lines += ["", "## Input Schema", "", "| Field | Type | Required | Default |", "|---|---|---|---|"]
        for field, spec in inp["schema"].items():
            lines.append(f"| {field} | {spec.get('type','any')} | {spec.get('required', False)} | {spec.get('default', '—')} |")

    out = tool.get("output", {}) or {}
    if out.get("schema"):
        lines += ["", "## Output Schema", "", "| Field | Type |", "|---|---|"]
        for field, spec in out["schema"].items():
            lines.append(f"| {field} | {spec.get('type','any')} |")

    (docs_dir / "tools" / f"{name}.md").write_text("\n".join(lines))